learningObjectives:
  - node/npm-install
  - node/package.json
  - node/npm-scripts
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/modules/commonjs
  - js/linting
  - js/semantics
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management
  - express/routing
  - express/middleware
  - http/request-response
  - http/body
  - http/verbs
  - http/status-codes
  - http/json
  - webops/cloud-functions
  - slack/slash-commands
