track: ux
tags:
  - featured
learningObjectives:
  - agile-planning/scope
  - agile-planning/workplan
  - agile-planning/tasks
  - business-understanding/business-model
  - business-understanding/goals-and-kpis
  - business-understanding/benchmark
  - research-planning
  - research-qualitative
  - research-quantitative
  - research-analysis
  - design-concept
  - interaction-design
  - content-design/voice-tone
  - content-design/micro-content
  - interface-design/visual-design
  - interface-design/accesibility
  - interface-design/responsive-design
  - design-prototype/basic-prototypes
  - design-prototype/high-fidelity
  - design-prototype/advanced-interactions
  - usability-analysis/moderated-testing
  - usability-analysis/heuristic-analysis
  - usability-analysis/non-moderated-testing
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/use-cases
  - design-specs/project-documentation
  - design-systems/atomic-design
  - design-systems/design-system
