learningObjectives:
  - js/async
  - js/testing/unit
  - js/testing/e2e
  - auth
  - http/request-response
  - http/verbs
  - http/cors
  - react
  - vue
  - angular
  - express/routing
  - express/service-creation
  - authorization
  - websockets
  - db/modeling
  - db/diagraming
  - db/sql-select
  - db/sql-insert-update-delete
  - db/indexes-constraints
  - cicd/build-pipelines
  - cicd/service-deployment
  - cicd/tbd
  - cicd/test-coverage
  - cicd/integration-tests
  - prod-dev/user-stories
  - prod-dev/acceptance-criteria
  - prod-dev/dod
  - prod-dev/iterative
  - prod-dev/invest
