track: ux
tags:
  - featured
learningObjectives:
  - agile-planning/tasks
  - agile-planning/workplan
  - business-understanding/benchmark
  - research-planning
  - research-quantitative/user-surveys
  - research-analysis/identify-patterns
  - research-analysis/process-information
  - research-analysis/synthesize-results
  - design-concept/design-references
  - design-concept/ideate
  - design-concept/prioritize-ideas
  - interaction-design/user-flows
  - interaction-design/usability
  - interface-design/visual-design
  - design-prototype/basic-prototypes
  - design-prototype/high-fidelity
  - usability-analysis/moderated-testing
  - usability-analysis/heuristic-analysis
  - design-pitch
  - design-specs/file-organization
  - design-specs/project-documentation
