learningObjectives:
  - user-centricity/user-oriented
  - user-centricity/prioritization
  - research/planning
  - research/support
  - research/guidelines
  - research/interview
  - research/documentation
  - research/adaptation
  - research/sources
  - synthesis/patterns
  - synthesis/mapping
  - synthesis/ideation
  - synthesis/feature-prioritization
  - product-design/user-flows
  - product-design/usability
  - product-design/visual-design
  - product-design/project-organization
  - communication/case-study
  - planning/monitor
  - planning/prioritization
  - planning/tools
  