track: ux
tags:
  - featured
learningObjectives:
  - agile-planning
  - business-understanding
  - research-planning
  - research-qualitative
  - research-quantitative
  - research-analysis
  - design-concept
  - interaction-design
  - content-design
  - interface-design
  - design-prototype
  - usability-analysis
  - design-pitch
  - design-specs
  - design-systems
