track: ux
learningObjectives:
  - agile-planning/scope
  - agile-planning/workplan
  - agile-planning/tasks
  - research-planning/research-plan
  - research-planning/research-sample
  - research-planning/participants
  - content-design/voice-tone
  - content-design/create-content
  - interface-design/visual-design
  - interface-design/accesibility
  - design-prototype/basic-prototypes
  - usability-analysis/non-moderated-testing
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/use-cases
  - design-specs/project-documentation
  - design-systems/atomic-design
