learningObjectives:
  - html/semantics
  - css/selectors
  - css/box-model
  - css/flexbox
  - css/grid
  - browser/dom/selectors
  - browser/dom/events
  - browser/dom/manipulation
  - browser/routing
  - js/data-types/arrays
  - js/data-types/objects
  - js/data-types/primitive-vs-non-primitive
  - js/variables
  - js/conditionals
  - js/loops
  - js/functions
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - js/expression-vs-statement
  - js/async/callbacks
  - js/async/promises
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  - scm/github/collaboration
  - scm/github/project-management
  - ux/user-understanding
  - ux/prototyping
  - ux/visual-design
  - ux/usability-testing
  - firebase/auth
  - firebase/firestore
