track: web-dev
learningObjectives:
  - http
  - auth
  - sql/crud
  - db/modeling
  - db/connection
  - postgres/data-types
  - postgres/indexes
  - scm/git
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management

# permite mayor control de la informacion en seleccion de proyecto
# se pretende tener una semantica predefinida q controle el comportamiento
# de la interfaz.
# por ahora estos son los unicos valores permitidos
tags:
  - featured

# para proyectos que tienen diferentes implementaciones (aka rutas)
variants:
  - name: java
    learningObjectives:
      - java
      - object-oriented-programming

  - name: node
    learningObjectives:
      - js/testing/unit
      - js/testing/async
      - js/testing/mocks
      - js/testing/e2e
      - js/modules/es-modules
      - js/modules/commonjs
      - js/linting
      - js/semantics
      - node/npm-install
      - node/package.json
      - node/npm-scripts
      - express/routing
      - express/middleware
      - id: typescript/basic-types/primitives
        optional: true
      - id: typescript/basic-types/arrays
        optional: true
      - id: typescript/basic-types/functions
        optional: true
      - id: typescript/basic-types/object-types
        optional: true
      - id: typescript/basic-types/union-types
        optional: true
      - id: typescript/basic-types/interfaces
        optional: true
      - id: typescript/basic-types/enums
        optional: true
      # Cualquier OA puede expresarse como objeto, por ejemplo para flaggear
      # como "opcional".
      # por ahora es la unica propiedad soportada.
      - id: object-oriented-programming
        optional: true

  - name: python
    learningObjectives:
      - python
      - id: python/django
        exclude: true
      - id: object-oriented-programming
        optional: true
      - id: sql/crud
        exclude: true
      - id: postgres/data-types
        exclude: true
      - id: postgres/indexes
        exclude: true

  - name: python-django
    learningObjectives:
      - python
      - id: python/flask
        exclude: true
      - id: sql/crud
        exclude: true
      - id: postgres/data-types
        exclude: true
      - id: postgres/indexes
        exclude: true

  - name: csharp
    learningObjectives:
      - csharp
      - id: object-oriented-programming
        optional: true
