track: web-dev
learningObjectives:
  - java
  - python
  - object-oriented-programming
  - node
  - sql
  - db
  - csharp
  - postgres/data-types
  - postgres/indexes
  - scm/git
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management
  - typescript/basic-types/primitives
  - typescript/basic-types/arrays
  - typescript/basic-types/functions
  - typescript/basic-types/object-types
  - typescript/basic-types/union-types
  - typescript/basic-types/interfaces
  - typescript/basic-types/enums
