track: web-dev
learningObjectives:
  - java
  - python
  - object-oriented-programming
  - node
  - sql
  - db
  - postgres/data-types
  - postgres/indexes
  - scm/git
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management
