track: web-dev
learningObjectives:
  - java
  - python
  - object-oriented-programming
  - node
  - sql
  - db
  - postgres/data-types
  - csharp/data-types/non-primitives
  - csharp/collections
  - csharp/access-modifiers
  - csharp/namespaces
  - csharp/functions
  - csharp/error-handling
  - csharp/async-await
  - csharp/.net-core
  - csharp/nuget-packages
  - csharp/testing
  - csharp/entity-framework
