html:
  # - tags
  # - attributes
  # - block-vs-inline
  - semantics

css:
  - selectors
  - box-model
  # - values-and-units
  # - relative-vs-absolute
  - flexbox
  - grid
  - media-queries

browser:
  - dom:
      - selectors
      - events
      - manipulation
  - routing
  - storage
  - fetch

js:
  - data-types:
      - primitive
      - primitive-vs-non-primitive
      # - values-and-refs
      # - typeof
      # - instanceof
      - strings
      - arrays
      - objects
  - variables
  - conditionals
  - loops
  - functions
  - recursion
  - testing:
      - unit
      # - cases
      # - assertions
      - mocks
      - async
      # - coverage
      - e2e
      - compatibility
  - modules:
      - es-modules
      - commonjs
  - linting
  - semantics
  - expression-vs-statement
  - async:
      - callbacks
      - promises
    # - async/await
    # - streams

java:
  - data-types:
      - primitive
      - primitive-vs-non-primitive
      - strings
      - arrays
      - void
      - enums
      - date
  - access-modifiers:
      - private
      - protected
      - public 
  - object-oriented:
      - classes-and-objects:
        - classes
        - objects
        - methods
        - attributes
        - constructors
        - encapsulation
      - abstraction
      - interface
      - polimorphism
      - inherit:
        - superclass
        - extends
        - override
  - variables
  - conditionals
  - loops
  - lambda
  - optional
  - stream
  - collections:
    - list:
      - arraylist
    - set:
      - hashset
    - map:
      - hashmap
  - exceptions

hibernate: 
  - setup
  - orm:
    - entity
    - table
    - columns
    - relationship:
      - manytoone
      - onetomany
      - manytomany
  - create
  - read
  - update
  - delete

spring:
  - core-concepts:
    - beans
    - inversion-of-control
    - annotations
  - spring-boot:
    - servlets
    - controllers
    - services
  - spring-data-jpa:
    - entities
    - repository
  - setup:
    - initializr
    - gradle
   

scm:
  - git:
      - setup
      - intro
      - integration
  - github:
      - setup
      - gh-pages
      - collaboration
      - project-management
      - ci

user-centricity:
  - centricity
  - user-oriented
  - prioritization
  
business:
  - model
  - goals
  - metrics
  - benchmark
  
synthesis:
  - weighing
  - patterns
  - insights
  - mapping
  - features
  - ideation
  - feature-prioritization

product-design:
  - user-flows
  - content
  - fidelity
  - interactivity
  - usability
  - accessibility
  - visual-design
  - component-organization
  - project-organization
  - documentation

communication:
  - presentation
  - negotiation
  - relationship-management
  - case-study

planning:
  - monitor
  - prioritization
  - tools
    
firebase:
  - auth
  - firestore

front-end-web-dev:
  - components
  - state
  # - routing

angular:
  - components-and-templates
  - structural-directives
  - input-output
  - services
  - routing
  - observables
  - http-client
  - styles

react:
  - jsx
  - components
  - events
  - lists-and-keys
  - conditional-rendering
  - lifting-up-state
  - hooks
  - css-modules
  - routing

vue:
  - instance
  - data-and-methods
  - components
  - props
  - directives
  - iteration
  - events
  - computed-props-and-observers
  - routing
  - classes-and-styles

http:
  - request-response
  - headers
  - body
  - verbs
  - status-codes
  - json
  - cors

node:
  - npm-install
  - package.json
  - npm-scripts
  - process
  - filesystem

express:
  - routing
  - middleware

socket-io:
  - client
  - server

auth:
  - jwt
  - password-access-and-storage

webops:
  - env-vars
  - docker-containers
  - docker-compose
  - cloud-functions

cicd:
  - build-pipelines
  - service-deployment
  - tbd
  - test-coverage
  - integration-tests

db:
  - modeling
  - connection
  - indexes-constraints
  # - diagramming
  # - cap-theorem
  # - sql-vs-nosql

sql:
  - tables
  - crud
  - drop

postgres:
  - psql
  - data-types
  - indexes
  - dump-restore

mysql:
  - mysql
  - data-types
  - indexes
  - dump-restore

mongodb:
  - crud
  - schemas
  - dump-restore
  # - aggregation
  # - transactions
  # - inedexes
  # - change-streams
  # - replication

slack:
  - slash-commands

php:
  - data-types:
      - primitive
      - arrays
      - objects
  - variables
  - control-structures
  - functions
  - testing:
      - phpunit
      - xdebug
  - package-management:
      - composer

wordpress:
  - plugin-development:
      - hooks
      - administration-menu
      - shortcodes
      - settings
      - custom-post-types
      - taxonomies
      - users
      - cron
      - wordpress-rest-api
      - wordpress-apis
      - wordpress-plugin-directory

typescript:
  - basic-types:
    - static-type-checking
    - strictness
    - primitives
    - arrays
    - any
    - functions
    - object-types:
      - optional-properties
    - union-types
    - type-aliases
    - interfaces
    - type-assertions
    - literal-types
    - null-and-undefined
    - enums
  - narrowing
  - classes:
    - members:
      - fields
      - constructor
      - methods
      - getter-setters
    - class-heritage:
      - implements
      - extends
    - member-visibility:
      - public
      - protected
      - private
    - static-members
    - this
    - abstract-classes
  - decorators

# New OAs since UXD006
agile-planning:
  - scope
  - workplan
  - tasks

business-understanding:
  - business-model
  - goals-and-kpis
  - benchmark

research:
  - support
  - guidelines
  - interview
  - documentation
  - adaptation
  - sources
  - test
  - cuantitative-data
  - planning:
    - research-plan
    - desk-research
    - research-sample
    - participants
  - qualitative:
    - user-interviews
    - exploratory-techniques
  - quantitative:
    - user-surveys
    - analytical-techniques
  - analysis:
    - process-information
    - experience-mapping
    - identify-patterns
    - synthesize-results

design-concept:
  - define-mvp
  - design-references
  - ideate
  - prioritize-ideas

interaction-design:
  - user-flows
  - usability
  - information-architecture

content-design:
  - voice-tone
  - create-content

interface-design:
  - visual-design
  - accesibility
  - responsive-design

design-prototype:
  - basic-prototypes
  - high-fidelity
  - advanced-interactions

usability-analysis:
  - moderated-testing
  - heuristic-analysis
  - non-moderated-testing

design-pitch:
  - design-feedback
  - design-presentation

design-specs:
  - file-organization
  - use-cases
  - project-documentation

design-systems:
  - atomic-design
  - design-system
