track: web-dev
learningObjectives:
  - data-types:
      - primitive
      - primitive-vs-non-primitive
      - strings
      - arrays
      - void
      - enums
      - date
  - access-modifiers:
      - private
      - protected
      - public
  - object-oriented:
      - classes-and-objects:
        - classes
        - objects
        - methods
        - attributes
        - constructors
        - encapsulation
      - uml:
        - class-diagram
      - abstraction
      - composition
      - interface
      - polimorphism
      - inherit:
        - superclass
        - extends
        - override
  - variables
  - conditionals
  - loops
  - lambda
  - optional
  - stream
  - collections:
    - list:
      - arraylist
