track: web-dev
learningObjectives:
  - java/data-types/primitive
  - java/data-types/primitive-vs-non-primitive
  - java/data-types/strings
  - java/data-types/arrays
  - java/data-types/void
  - java/data-types/enums
  - java/data-types/date
  - java/access-modifiers/private
  - java/access-modifiers/protected
  - java/access-modifiers/public
  - java/object-oriented/classes-and-objects/classes
  - java/object-oriented/classes-and-objects/objects
  - java/object-oriented/classes-and-objects/methods
  - java/object-oriented/classes-and-objects/attributes
  - java/object-oriented/classes-and-objects/constructors
  - java/object-oriented/classes-and-objects/encapsulation
  - java/object-oriented/uml/class-diagram
  - java/object-oriented/uml/abstraction
  - java/object-oriented/uml/composition
  - java/object-oriented/uml/interface
  - java/object-oriented/uml/polymorphism
  - java/object-oriented/inherit/superclass
  - java/object-oriented/inherit/extends
  - java/object-oriented/inherit/override
  - java/variables
  - java/conditionals
  - java/loops
  - java/lambda
  - java/optional
  - java/stream
  - java/collections/list/arraylist
