track: ux
tags:
  - deprecated
learningObjectives:
  - agile-planning/scope
  - agile-planning/workplan
  - agile-planning/tasks
  - research-planning
  - research-quantitative
  - research-analysis
  - interaction-design
  - content-design/voice-tone
  - content-design/micro-content
  - design-prototype/basic-prototypes
  - usability-analysis/non-moderated-testing
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/project-documentation
