track: ux
learningObjectives:
  - agile-planning/scope
  - agile-planning/workplan
  - agile-planning/tasks
  - research/planning/research-plan
  - research/planning/research-sample
  - research/planning/participants
  - research/quantitative/user-surveys
  - research/quantitative/analytical-techniques
  - research/analysis/process-information
  - research/analysis/experience-mapping
  - research/analysis/identify-patterns
  - research/analysis/synthesize-results
  - interaction-design/user-flows
  - interaction-design/usability
  - interaction-design/information-architecture
  - content-design/voice-tone
  - content-design/create-content
  - design-prototype/basic-prototypes
  - usability-analysis/non-moderated-testing
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/project-documentation
