module.exports = [
  {
    category: 'UX',
    objectives: [
      'Diseñar la aplicación pensando y entendiendo al usuario.',
      'Crear prototipos para obtener feedback e iterar.',
      'Aplicar los principios de diseño visual (contraste, alineación, jerarquía).',
      'Planear y ejecutar tests de usabilidad.',
    ],
  },
  {
    category: 'HTML, CSS',
    objectives: [
      'Uso de HTML semántico.',
      'Uso de selectores de CSS.',
      'Construir tu aplicación respetando el diseño realizado (maquetación).',
      'Uso de flexbox en CSS.',
      'Uso de Media Queries.',
      'Sass',
    ],
  },
  {
    category: 'DOM',
    objectives: [
      'Uso de selectores del DOM.',
      'Manejo de eventos del DOM.',
      'Manipulación dinámica del DOM (appendChild |createElement | createTextNode| innerHTML | textContent | etc.).',
      'History API',
      'Localstorage',
    ],
  },
  {
    category: 'Javascript',
    objectives: [
      'Manipulación de strings.',
      'Uso de condicionales (if-else | switch | operador ternario).',
      'Uso de bucles (for | for..in | for..of | while).',
      'Uso de funciones (parámetros | argumentos | valor de retorno).',
      'Declaración correcta de variables (const & let).',
      'Manipular arrays (filter | map | sort | reduce).',
      'Manipular objects (key | value).',
      'Uso de ES Modules (import | export).',
      'Diferenciar entre expression y statements.',
      'Diferenciar entre tipos de datos atómicos y estructurados.',
      'Uso de Callbacks',
      'Consumo de Promesas',
      'Creación de Promesas.',
    ],
  },
  {
    category: 'Node',
    objectives: [
      'Uso de sistema de archivos.',
      'Instalar y usar modules.',
      'Creación de modules.',
      'Configuración de package.json',
      'Configuración de npm scripts.',
      'Uso de CLI (Command Line Interface - Interfaz de Línea de Comando)',
    ],
  },
  {
    category: 'Testing',
    objectives: [
      'Testeo unitario.',
      'Testeo asíncrono.',
      'Uso de librerias de Mock.',
      'Uso de Mocks manuales.',
      'Testeo para múltiples Sistemas Operativos.',
      'Test de integración.',
    ],
  },
  {
    category: 'Estructura de código',
    objectives: ['Organizar y dividir el código en módulos (Modularización).'],
  },
  {
    category: 'Guia de estilo',
    objectives: [
      'Uso de identificadores descriptivos (Nomenclatura | Semántica).',
      'Uso de linter (ESLINT).',
    ],
  },
  {
    category: 'Git, GitHub',
    objectives: [
      'Uso de comandos de git (add | commit | pull | status | push).',
      'Manejo de repositorios de GitHub (clone | fork | gh-pages).',
      'Organización en Github (projects | issues | labels | milestones)',
    ],
  },
  {
    category: 'Firebase',
    objectives: [
      'Firestore',
      'Firebase Auth',
      'Firebase security rules',
      'Observables',
    ],
  },
  {
    category: 'Front-end Development',
    objectives: ['Uso de Componentes', 'Manejo del estado'],
  },
  { category: 'Express', objectives: ['Rutas', 'middlewares'] },
  {
    category: 'HTTP',
    objectives: [
      'Request, Response',
      'Headers',
      'Body',
      'Verbos HTTP',
      'Códigos de status HTTP',
      'Encodings y JSON',
      'CORS',
    ],
  },
  {
    category: 'Autenticación',
    objectives: ['JWT', 'Almacenamiento y acceso de contraseñas'],
  },
  {
    category: 'Servidores',
    objectives: ['Variables de entorno', 'SSH', 'SSH Keys', 'VPS'],
  },
  {
    category: 'Base de datos',
    objectives: [
      'Instalación',
      'Conexión a través de cliente',
      'Connection String',
      'Queries y comandos',
    ],
  },
  {
    category: 'Deployment',
    objectives: ['Contenedores', 'Docker', 'Docker compose'],
  },
  {
    category: 'Angular',
    objectives: [
      'Components y templates',
      'Directivas estructurales ngIf/ngFor',
      '@input / @output',
      'Creación y uso de servicios',
      'Manejo de Rutas',
      'Uso de Observables',
      'Uso de HttpClient',
      'Estilo de componentes ngStyle/ngClass',
    ],
  },
  {
    category: 'React',
    objectives: [
      'JSX',
      'Componentes class y componentes function',
      'props',
      'Eventos en React',
      'Listas y keys',
      'Renderizado condicional',
      'Elevación de estado',
      'hooks',
      'CSS modules',
      'react-router',
    ],
  },
  {
    category: 'Vue',
    objectives: [
      'Instancia de Vue.js',
      'Datos y métodos',
      'Uso y creación de Componentes',
      'Props',
      'Directivas v-bind y v-model',
      'Renderizado condicional v-if y v-else',
      'Iteraciones v-for',
      'Eventos v-on',
      'Propiedades computadas y observadores',
      'Router',
      'Clases y estilos',
    ],
  },
  {
    category: 'Fundamentos',
    objectives: [
      'Recursión',
      'Asignación por valor y por referencia',
      'Expresión / sentencia',
      'Hoisting (énfasis es declaración de funciones)',
      'Declaración vs ejecución de una función',
      'Objetos literales',
      'Call-stack en JavaScript',
      'Timeouts',
      'Variables (valores) y ámbito',
    ],
  },
];
