learningObjectives:
  - html/semantics
  - css/selectors
  - css/box-model
  - css/flexbox
  - css/grid
  - css/media-queries
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  - scm/github/collaboration
  - scm/github/project-management
  - http
  - angular
  - react
  - vue
  - ux/user-understanding
  - ux/prototyping
  - ux/visual-design
  - ux/usability-testing
