track: web-dev
tags:
  - hidden
learningObjectives:
  - html/semantics
  - css/selectors
  - css/box-model
  - css/flexbox
  - css/grid
  - css/media-queries
  - js/data-types/arrays
  - js/data-types/objects
  - js/data-types/primitive-vs-non-primitive
  - js/conditionals
  - js/functions
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  #- js/modules/es-modules
  - js/linting
  - js/semantics
  - js/expression-vs-statement
  #- js/async/callbacks
  #- js/async/promises
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  #- scm/github/collaboration
  #- scm/github/project-management
  - user-centricity/centricity
  - product-design/interactivity
  - product-design/visual-design
  #- research/test
  - firebase/auth
  - firebase/firestore
  - angular
  - react
  - vue
