track: ux
tracks:
  - ux
learningObjectives:
  - agile-planning/tasks
  - design-concept/ideate
  - design-concept/prioritize-ideas
  - interaction-design/user-flows
  - interface-design/visual-design
  - design-prototype/basic-prototypes
  - design-specs/project-documentation
