track: web-dev
learningObjectives:
  - java/data-types/primitive-vs-non-primitive
  - java/data-types/strings
  - java/data-types/arrays
  - java/access-modifiers (public, private, protected)
  - java/conditionals
  - java/loops
  - java/collections/array-list
  - java/collections/hash-map
  - java/collections/hash-set
  - object-oriented-programming/classes
  - object-oriented-programming/objects
  - object-oriented-programming/methods
  - object-oriented-programming/attributes
  - object-oriented-programming/constructors
  - object-oriented-programming/encapsulation
  - object-oriented-programming/abstraction
  - object-oriented-programming/composition
  - object-oriented-programming/interfaces
  - object-oriented-programming/inheritance (super extends override)
  - object-oriented-programming/unified-model-language (class diagrams)
  - java/testing/junit
  - java/testing/mockito
  - java/spring-framework/initializr
  - java/spring-framework/beans
  - java/spring-framework/inversion-of-control
  - java/spring-framework/spring-boot
  - java/spring-framework/servlets
  - java/spring-framework/controllers
  - java/spring-framework/services
  - java/spring-framework/spring-data-jpa
  - java/spring-framework/entity
  - java/spring-framework/initializr
  - java/spring-framework/repository
  - java/spring-framework/spring-web/rest-controller
  - java/spring-framework/spring-web/request-mapping
  - java/spring-framework/spring-web/request-param
  - java/spring-framework/testing/spring-test
  - java/spring-framework/testing/hamcrest
  - java/hibernate-orm/setup
  - java/hibernate-orm/schema
  - java/hibernate-orm/entity
  - java/hibernate-orm/table
  - java/hibernate-orm/column
  - java/hibernate-orm/identifiers
  - java/hibernate-orm/associations
  - java/hibernate-orm/collections
  - java/hibernate-orm/persistance
  - java/hibernate-orm/querying
