track: ux
learningObjectives:
  - agile-planning/tasks
  - business-understanding/benchmark
  - research/analysis/synthesize-results
  - design-concept/define-mvp
  - design-concept/design-references
  - design-concept/ideate
  - design-concept/prioritize-ideas
  - interaction-design/user-flows
  - interaction-design/usability
  - interaction-design/information-architecture
  - interface-design/visual-design
  - interface-design/accesibility
  - design-prototype/basic-prototypes
  - usability-analysis/moderated-testing
  - usability-analysis/heuristic-analysis
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/use-cases
  - design-specs/project-documentation
