track: ux
learningObjectives:
  - agile-planning/tasks
  - business-understandig/benchmark
  - research-analysis/synthesizeResults

  - design-concept/defineMVP
  - design-concept/designReferences
  - design-concept/ideate
  - design-concept/prioritizeIdeas

  - interaction-design/userFlows
  - interaction-design/usability
  - interaction-design/informationArchitecture

  - interface-design/visualDesign
  - interface-design/accesibility

  - design-prototype/basicPrototypes

  - design-validation/moderatedTesting
  - design-validation/heuristicAnalysis

  - design-pitch/designFeedback
  - design-pitch/designPresentation

  - design-specs/fileOrganization
  - design-specs/useCases
  - design-specs/projectDocumentation