track: web-dev
learningObjectives:
  - html/semantics
  - css/selectors
  - css/box-model
  - css/flexbox
  - css/grid
  - css/media-queries
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  - scm/github/collaboration
  - scm/github/project-management
  - http
  - angular
  - react
  - vue
  - typescript/basic-types/primitives
  - typescript/basic-types/arrays
  - typescript/basic-types/functions
  - typescript/basic-types/object-types
  - typescript/basic-types/union-types
  - typescript/basic-types/interfaces
  - typescript/basic-types/enums
  - user-centricity/centricity
  - product-design/interactivity
  - product-design/visual-design
  - research/test
