learningObjectives:
  - user-centricity/user-oriented
  - user-centricity/prioritization
  - business/goals
  - business/benchmark
  - research/planning
  - research/sources
  - synthesis/ideation
  - product-design/content
  - product-design/usability
  - product-design/accessibility
  - product-design/visual-design
  - product-design/component-organization
  - communication/case-study
  - planning/prioritization
  - planning/tools