version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./html:/var/www/html
      - ./php-playground:/var/www/php-playground
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./apache2/sites-available:/etc/apache2/sites-available
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./logs/:/var/log/apache2
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  #alias wp-docker="docker-compose run --rm wp"
  #docker-compose rm wpcli && docker-compose up -d && docker-compose run --rm wpcli
  wp:
    depends_on:
      - wordpress
    image: wordpress:cli
    volumes_from:
      - wordpress
    links:
      - db:mysql
    user: "33"
    entrypoint: wp
    command: "--info"
    working_dir: /var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
    - 8888:80
    environment:
    - PMA_ARBITRARY=1

  phpunit:
    image: "chriszarate/wordpress-phpunit:6.0.6"
    volumes:
      - "./html/wp-content/plugins:/app"
      - "testsuite:/tmp"

volumes:
  db_data: {}
  testsuite: {}
