learningObjectives:
  - ux/user-centricity/centricity
  - ux/user-centricity/persistency
  - ux/research/support
  - ux/research/documentation
  - ux/research/sources
  - ux/research/test
  - ux/synthesis/patterns
  - ux/synthesis/features
  - ux/synthesis/feature-prioritization
  - ux/product-design/content
  - ux/product-design/usability
  - ux/product-design/visual-design
  - ux/planning/monitor
  - ux/planning/prioritization