learningObjectives:
  - user-centricity/persistency
  - research/support
  - research/documentation
  - research/sources
  - research/test
  - synthesis/patterns
  - synthesis/features
  - synthesis/feature-prioritization
  - product-design/content
  - product-design/usability
  - product-design/visual-design
  - planning/monitor
  - planning/prioritization