learningObjectives:
  - user-centricity/centricity
  - user-centricity/persistency
  - user-centricity/prioritization
  - business/alignment
  - business/model
  - business/goals
  - business/metrics
  - business/benchmark
  - research/planning
  - research/support
  - research/guidelines
  - research/interview
  - research/documentation
  - research/adaptation
  - research/sources
  - research/test
  - research/analytics
  - research/cuantitative-data
  - synthesis/weighing
  - synthesis/patterns
  - synthesis/insights
  - synthesis/mapping
  - synthesis/features
  - synthesis/ideation
  - synthesis/feature-prioritization
  - product-design/user-flows
  - product-design/content
  - product-design/fidelity
  - product-design/interactivity
  - product-design/usability
  - product-design/accessibility
  - product-design/visual-design
  - product-design/component-organization
  - product-design/project-organization
  - product-design/documentation
  - product-design/naming
  - product-design/handoff
  - communication/presentation
  - communication/negotiation
  - communication/relationship-management
  - planning/monitor
  - planning/prioritization
  - planning/tools