name: Talent Fest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install flowise
        run: npm install -g flowise

      - name: install wait-on
        run: npm install -g wait-on

      - name: install dependencies
        run: npm install

      - name: main
        run: npx flowise start &
          wait-on tcp:3000 &&
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} npm run load &&
          npm test
