track: ux
learningObjectives:
  - agile-planning/tasks
  - design-concept/ideate
  - design-concept/prioritizeIdeas
  - interaction-design/userFlows
  - interface-design/visualDesign
  - design-prototype/basicPrototypes
  - design-specs/projectDocumentation