learningObjectives:
  - user-centricity/prioritization
  - business/goals
  - research/planning
  - research/guidelines
  - research/interview
  - research/documentation
  - research/adaptation
  - research/sources
  - synthesis/patterns
  - synthesis/insights
  - communication/case-study
  - planning/monitor
  - planning/prioritization
  - planning/tools