learningObjectives:
  - user-centricity/centricity
  - user-centricity/persistency
  - user-centricity/prioritization
  - business/alignment
  - business/benchmark
  - research/sources
  - research/test
  - synthesis/ideation
  - product-design/user-flows
  - product-design/content
  - product-design/fidelity
  - product-design/interactivity
  - product-design/usability
  - product-design/accessibility
  - product-design/visual-design
  - product-design/component-organization
  - product-design/interface-guidelines
  - product-design/project-organization
  - product-design/documentation
  - product-design/naming
  - product-design/handoff
  - planning/monitor
  - planning/prioritization
  - planning/tools