learningObjectives:
  - ux/user-centricity/centricity
  - ux/user-centricity/persistency
  - ux/user-centricity/prioritization
  - ux/business/alignment
  - ux/business/benchmark
  - ux/research/sources
  - ux/research/test
  - ux/synthesis/ideation
  - ux/product-design/user-flows
  - ux/product-design/content
  - ux/product-design/fidelity
  - ux/product-design/interactivity
  - ux/product-design/usability
  - ux/product-design/accessibility
  - ux/product-design/visual-design
  - ux/product-design/component-organization
  - ux/product-design/interface-guidelines
  - ux/product-design/project-organization
  - ux/product-design/documentation
  - ux/product-design/naming
  - ux/product-design/handoff
  - ux/planning/monitor
  - ux/planning/prioritization
  - ux/planning/tools