track: web-dev
learningObjectives:
  - node/npm-install
  - node/package.json
  - node/npm-scripts
  - node/process
  - js/data-types
  - js/variables
  - js/conditionals
  - js/loops
  - js/functions
  - js/testing/unit
  - js/modules/commonjs
  - js/linting
  - js/semantics
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management
