learningObjectives:
  - product-design/interactivity
  - product-design/visual-design
  - product-design/component-organization
  - product-design/project-organization
  - planning/monitor
  - planning/prioritization
  - planning/tools
