learningObjectives:
  - browser/dom/selectors
  - browser/dom/events
  - browser/dom/manipulation
  - js/data-types/primitive
  - js/data-types/strings
  - js/variables
  - js/conditionals
  - js/loops
  - js/functions
  - js/semantics
