track: ux
tags:
  - featured
learningObjectives:
  - agile-planning/workplan
  - agile-planning/tasks
  - business-understanding/business-model
  - business-understanding/goals-and-kpis
  - business-understanding/benchmark
  - research-planning
  - research-qualitative/user-interviews
  - research-analysis
  - design-concept
  - interaction-design
  - content-design/micro-content
  - interface-design/visual-design
  - interface-design/accesibility
  - design-prototype/basic-prototypes
  - design-prototype/high-fidelity
  - usability-analysis/moderated-testing
  - usability-analysis/heuristic-analysis
  - design-pitch/design-feedback
  - design-pitch/design-presentation
  - design-specs/file-organization
  - design-specs/use-cases
  - design-specs/project-documentation
  - design-systems/atomic-design
