track: web-dev
learningObjectives:
  - data-analytics/analysis-presentation

tags:
  - featured

variants:
  - name: looker-studio
    learningObjectives:
      - id: data-analytics/power-bi
        exclude: true    
      - data-analytics
  
  - name: power-bi
    learningObjectives:
      - id: data-analytics/looker-studio
        exclude: true    
      - data-analytics
