learningObjectives:
  - node
  - express
  - db
  - pasarela pago
  - modelado de datos
  - arquitectura de información
  - persistencia de datos
  - consumo de datos (queries)
  - arquitectura de software
  - JSX
  - prisma CRUD operations
  - graphQL/schema modeling
  - graphQL/queries and mutations
  - http operations (GET, POST, PUT, PATCH, DELETE)
  - apollo/query modeling
  - apollo/react hooks
  - apollo/'state management'
  - js/data-types/arrays
  - js/data-types/objects
  - js/data-types/primitive-vs-non-primitive
  - js/conditionals
  - js/functions
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - js/expression-vs-statement
  - js/async/callbacks
  - js/async/promises
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/collaboration
  - scm/github/project-management
  - ux/user-understanding
  - ux/prototyping
  - ux/visual-design
  - ux/usability-testing