browser:
  - dom:
    - selectors
    - events
    - manipulation
  - routing
  - storage
  - fetch

js:
  - data-types:
    - primitive
    - primitive-vs-non-primitive
    # - values-and-refs
    # - typeof
    # - instanceof
    - strings
    - arrays
    - objects
  - variables
  - conditionals
  - loops
  - functions
  - recursion
  - testing:
    - unit
    # - cases
    # - assertions
    - mocks
    - async
    # - coverage
    - e2e
    - compatibility
  - modules:
    - es-modules
    - commonjs
  - linting
  - semantics
  - expression-vs-statement
  - async:
    - callbacks
    - promises
    # - async/await
    # - streams

scm:
  - git:
    - setup
    - intro
    - integration
  - github:
    - setup
    - gh-pages
    - collaboration
    - project-management
    - ci

ux:
  - user-understanding
  - prototyping
  - visual-design
  - usability-testing


front-end-web-dev:
  - components
  - state
  # - routing

react:
  - jsx
  - components
  - events
  - lists-and-keys
  - conditional-rendering
  - lifting-up-state
  - hooks
  - css-modules
  - routing
  - apollo
  - graphql queries

http:
  - request-response
  - headers
  - body
  - verbs
  - status-codes
  - json
  - cors

node:
  - npm-install
  - package.json
  - npm-scripts
  - process
  - filesystem

express:
  - routing
  - middleware

auth:
  - jwt
  - password-access-and-storage

webops:
  - env-vars
  - docker-containers
  - docker-compose
  - cloud-functions

db:
  - install
  - conection
  - queries
  - prisma
  - graphql schema
