learningObjectives:
  - js/data-types/primitive-vs-non-primitive
  - js/data-types/arrays
  - js/data-types/objects
  - js/conditionals
  - js/functions
  - js/recursion
  - js/modules/commonjs
  - js/expression-vs-statement
  - js/async/callbacks
  - js/async/promises
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/testing/compatibility
  - js/linting
  - js/semantics
  - node/npm-install
  - node/package.json
  - node/npm-scripts
  - node/process
  - node/filesystem
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  - scm/github/collaboration
  - scm/github/project-management
  - http/request-response
  - http/status-codes
